options = {}
options["RNN_type"]="vanilla"
options['n_hidden_output_neurons'] = 128
options['n_hidden_middle_neurons'] = 128
options['learning_rate'] = 0.0001
options['training_split'] = 0.9
options['batch_size'] = 200
options['n_batches'] = 5000
options['n_layers'] = 3
options['n_size'] = [8, 8, 8]
options['bidirectional'] = False
